### ISSUE TITLE
Crypto is not defined

### ISSUE THREAD

**Issue by Extarys** [auth70/paseto-ts#1]
When using on node v16.17, simply importing the library and calling `generateKeys` generate the following:
```
[unhandledRejection] ReferenceError: crypto is not defined 
    at generateKeys (file://.../node_modules/paseto-ts/dist/v4/key.js:11:13)
```

**Comment by miunau** [comment]
Hi, thanks for raising the issue. I'd only tested with Node 19, but made some changes so that on Node < 19 you'll need to pass an implementation for `getRandomValues`. Please see the updated readme:

https://github.com/auth70/paseto-ts#note-on-node-versions-under-19
