### ISSUE TITLE
is this library compatible with a cloudflare worker runtime ?

### ISSUE THREAD

**Issue by ymolists** [auth70/paseto-ts#10]
Hi folks. 

Thank you so much open sourcing this library.

I am super new to the web frontend but need to use paseto on the edge or more specifically on cloudflare workers for a side project. is this library going to work on workers runtime or there are limitations that i should be aware before embarking on this journey ?

Best Regards

**Comment by miunau** [comment]
Yes, it is compatible with CF workers.

**Comment by ymolists** [comment]
Thank you for the quick answer !
