### ISSUE TITLE
globalThis.crypto causes ERR_INVALID_THIS in Node 19.4.0

### ISSUE THREAD

**Issue by JohnnyRacer** [auth70/paseto-ts#2]
Hello, I tried using this library to generate some PASETO tokens but ran into an issue where it would give the following error:
```javascript
TypeError [ERR_INVALID_THIS]: Value of "this" must be of type Crypto
```
By passing the actual function from the `crypto` module solved my problem like so `const token = await encrypt(encryptKey, {'hello' : 'world'},{getRandomValues : crypto.getRandomValues});`.

**Comment by miunau** [comment]
Thanks for raising the issue. I've removed the usage in 6ba686f
